/**
 * Multiple Choice Questions: "A Modest Proposal" by Jonathan Swift
 * Source: Project Gutenberg (gutenberg.org) - Book #1080
 * Generated by Papersaurus AI Educational Tools
 * 
 * Each question has 5 options (A-E) with exactly one correct answer.
 * See answers.js for detailed explanations of all options.
 */

const questions = [
  {
    "id": 1,
    "question": "What type of literary work is 'A Modest Proposal'?",
    "options": {
      "A": "A novel",
      "B": "A satirical essay",
      "C": "An epic poem",
      "D": "A short story",
      "E": "A political speech"
    },
    "correctAnswer": "B"
  },
  {
    "id": 2,
    "question": "What is the shocking 'modest proposal' that Jonathan Swift satirically suggests?",
    "options": {
      "A": "Exiling all poor Irish families to the American colonies",
      "B": "Forcing the poor to work in British factories without pay",
      "C": "Selling Irish children as food to wealthy citizens",
      "D": "Taxing the wealthy to fund orphanages across Ireland",
      "E": "Banning all Irish exports to reduce British dependency"
    },
    "correctAnswer": "C"
  },
  {
    "id": 3,
    "question": "In what year was 'A Modest Proposal' published?",
    "options": {
      "A": "1684",
      "B": "1710",
      "C": "1729",
      "D": "1745",
      "E": "1759"
    },
    "correctAnswer": "C"
  },
  {
    "id": 4,
    "question": "What specific type of satire is 'A Modest Proposal' classified as?",
    "options": {
      "A": "Horatian satire",
      "B": "Menippean satire",
      "C": "Juvenalian satire",
      "D": "Socratic satire",
      "E": "Aristophanic satire"
    },
    "correctAnswer": "C"
  },
  {
    "id": 5,
    "question": "Which of the following is NOT a target of Swift's satirical critique in the essay?",
    "options": {
      "A": "Anti-Catholic sentiment in Ireland and Britain",
      "B": "British colonial governance of Ireland",
      "C": "Exploitation by wealthy landowners",
      "D": "The French monarchy's extravagant spending",
      "E": "Irish inaction on their own societal problems"
    },
    "correctAnswer": "D"
  },
  {
    "id": 6,
    "question": "What literary device does Swift primarily use by presenting his horrific proposal in a calm, rational tone?",
    "options": {
      "A": "Alliteration",
      "B": "Deadpan irony",
      "C": "Foreshadowing",
      "D": "Onomatopoeia",
      "E": "Allegory"
    },
    "correctAnswer": "B"
  },
  {
    "id": 7,
    "question": "What two societal problems does Swift's proposal satirically claim to solve?",
    "options": {
      "A": "Illiteracy and religious conflict",
      "B": "Poverty and overpopulation",
      "C": "Disease and warfare",
      "D": "Famine and political corruption",
      "E": "Unemployment and crime"
    },
    "correctAnswer": "B"
  },
  {
    "id": 8,
    "question": "What broader theme does Swift explore through his dehumanizing proposal about the poor?",
    "options": {
      "A": "The glory of the British Empire",
      "B": "The importance of scientific advancement",
      "C": "The dehumanization and exploitation of the lower class",
      "D": "The benefits of free-market economics",
      "E": "The moral superiority of the aristocracy"
    },
    "correctAnswer": "C"
  },
  {
    "id": 9,
    "question": "What does the phrase 'a modest proposal' conventionally signify in modern English usage?",
    "options": {
      "A": "A humble and sincere suggestion",
      "B": "A political compromise between opposing parties",
      "C": "An allusion to deadpan or understated satire",
      "D": "A formal academic thesis statement",
      "E": "A charitable initiative for the underprivileged"
    },
    "correctAnswer": "C"
  },
  {
    "id": 10,
    "question": "Swift's use of hyperbole — suggesting children be eaten — primarily serves what purpose?",
    "options": {
      "A": "To entertain readers with absurd comedy",
      "B": "To literally advocate for population control measures",
      "C": "To expose and mock the cruel attitudes of those in power toward the Irish poor",
      "D": "To demonstrate his personal hatred of children",
      "E": "To promote vegetarianism as a moral alternative"
    },
    "correctAnswer": "C"
  }
];

module.exports = { questions };
